bot_token = "PUT TOKER here"
report_channel = "" # the channel id where bot sends deleted or suspicious messages

messages_keep_track_count = 10000 # number of messaged to keep track of

moderated_channels = [
    "12345678", # general
    "78901234", # random
    "56789432", # another-channel
]

[features]
    # When someone deletes its message it is posted to the ${report_channel}
    [features.report_deleted_messages]
        enabled = true
        # messages deleted by members of below roles won't be reported
        whitelisted_roles = [
            "Admins",
            "Validators"
        ]


    # When any of given in the ${moderated_keywords} keyword is present in the new mesasge it is reported to the ${report_channel}
    [features.suspicious_messages]
        enabled = true
        keywords = [
            "pm",
            "support",
            "ticket",
            "dm",
        ]

        # messages sent by members of below roles won't be reported
        whitelisted_roles = [
            "Admins",
            "Validators"
        ]

    # When some one posts the discord invitation it is removed
    [features.delete_invite_links]
        enabled = true
        # messages with invitations by members of below roles won't be deleted
        whitelisted_roles = [
            "Admins",
            "Validators"
        ]